In [1]:
import tensorflow as tf

In [5]:
a = tf.random.normal([4, 3, 2, 1])

In [6]:
a.shape

TensorShape([4, 3, 2, 1])

In [8]:
tf.transpose(a).shape

TensorShape([1, 2, 3, 4])

In [9]:
tf.transpose(a, perm=[0, 1, 3, 2]).shape

TensorShape([4, 3, 1, 2])

In [12]:
a = tf.random.normal([4, 35, 8])

In [14]:
tf.expand_dims(a, axis=0).shape

TensorShape([1, 4, 35, 8])

In [15]:
tf.expand_dims(a, axis=3).shape

TensorShape([4, 35, 8, 1])

In [16]:
tf.expand_dims(a, axis=-1).shape

TensorShape([4, 35, 8, 1])

In [20]:
tf.expand_dims(a, axis=-2).shape

TensorShape([4, 35, 1, 8])

In [21]:
tf.squeeze(tf.zeros([1, 2, 1, 1, 3])).shape

TensorShape([2, 3])

In [22]:
b = tf.fill([2, 2], 2.0)
a = tf.ones([2, 2])

In [23]:
a + b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 3.],
       [3., 3.]], dtype=float32)>

In [24]:
a - b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1., -1.],
       [-1., -1.]], dtype=float32)>

In [25]:
a * b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [26]:
a / b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0.5],
       [0.5, 0.5]], dtype=float32)>

In [27]:
b // a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [28]:
b % a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [29]:
tf.math.log(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [33]:
tf.math.log(8.0) / tf.math.log(2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [34]:
tf.math.log(100.0) / tf.math.log(10.0)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [36]:
tf.pow(b, 3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [37]:
b ** 3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 8.],
       [8., 8.]], dtype=float32)>

In [39]:
tf.sqrt(b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.4142135],
       [1.4142135, 1.4142135]], dtype=float32)>

In [40]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [42]:
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>

In [44]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [63]:
a = tf.ones([4, 2, 3])
b = tf.fill([3, 5], 2.0)

In [53]:
a.shape

TensorShape([4, 2, 3])

In [54]:
b.shape

TensorShape([3, 5])

In [64]:
bb = tf.broadcast_to(b, [4, 3, 5])
bb.shape

TensorShape([4, 3, 5])

In [65]:
a @ bb

<tf.Tensor: shape=(4, 2, 5), dtype=float32, numpy=
array([[[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]]], dtype=float32)>