In [3]:
import tensorflow as tf

# import os
# os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
print(len(x_train))

60000


In [13]:
x = tf.random.normal([2, 3])
print(x)
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(2, activation='relu'),
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(2),
])



model.build(input_shape=[None, 3])
model.summary()

tf.Tensor(
[[ 0.25054464  0.30308232  0.27538857]
 [ 1.7699292  -0.7946703  -0.17306483]], shape=(2, 3), dtype=float32)
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 2)                 8         
_________________________________________________________________
dense_8 (Dense)              (None, 10)                30        
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 22        
Total params: 60
Trainable params: 60
Non-trainable params: 0
_________________________________________________________________


In [15]:
for p in model.trainable_variables:
    print(p.name, p.shape)

dense_7/kernel:0 (3, 2)
dense_7/bias:0 (2,)
dense_8/kernel:0 (2, 10)
dense_8/bias:0 (10,)
dense_9/kernel:0 (10, 2)
dense_9/bias:0 (2,)


In [19]:
a = tf.linspace(-6, 6, 10)
tf.sigmoid(a)

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.00247262, 0.00931596, 0.0344452 , 0.11920292, 0.33924363,
       0.66075637, 0.88079708, 0.9655548 , 0.99068404, 0.99752738])>

In [22]:
x = tf.random.normal([1, 28, 28]) * 5
tf.reduce_min(x), tf.reduce_max(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=-17.631859>,
 <tf.Tensor: shape=(), dtype=float32, numpy=15.854765>)

In [23]:
x = tf.sigmoid(x)
tf.reduce_min(x), tf.reduce_max(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=2.200802e-08>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.0>)

In [28]:
b = tf.nn.softmax(a)
b

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([4.52462289e-06, 1.71649166e-05, 6.51179930e-05, 2.47036039e-04,
       9.37172691e-04, 3.55532195e-03, 1.34877107e-02, 5.11678952e-02,
       1.94114001e-01, 7.36404055e-01])>

In [32]:
y = tf.constant([1, 2, 3, 0, 2])
y = tf.one_hot(y, depth=4)
y

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)>