In [1]:
import tensorflow as tf

In [3]:
a = tf.ones([1, 5, 5, 3])

In [8]:
a[0][0][0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [10]:
a[0][0][0][2]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [12]:
a = tf.random.normal([4, 28, 28, 3])

In [14]:
a[1].shape

TensorShape([28, 28, 3])

In [16]:
a[1, 2].shape

TensorShape([28, 3])

In [18]:
a[1, 2, 3].shape

TensorShape([3])

In [20]:
a[1, 2, 3, 2].shape

TensorShape([])

In [22]:
a[1, 2, 3, 2]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.25466928>

In [24]:
a = tf.range(10)

In [25]:
a

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [26]:
a[-1:]

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([9], dtype=int32)>

In [27]:
a[-2:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 9], dtype=int32)>

In [28]:
a[:-1]

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [29]:
a[1: -1]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [30]:
a = tf.random.normal([4, 28, 28, 3])

In [31]:
a[0].shape

TensorShape([28, 28, 3])

In [32]:
a[0, 1, :, :].shape

TensorShape([28, 3])

In [35]:
a[:, :, :, 0].shape

TensorShape([4, 28, 28])

In [36]:
a[:, 0, :, :].shape

TensorShape([4, 28, 3])

In [38]:
a[::2, :, :, :].shape

TensorShape([2, 28, 28, 3])

In [43]:
a[:, 0:13:3, :, :].shape

TensorShape([4, 5, 28, 3])

In [57]:
a = tf.range(4) * 2 + 2

In [58]:
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 4, 6, 8], dtype=int32)>

In [59]:
a[::-1]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([8, 6, 4, 2], dtype=int32)>

In [60]:
a[::-2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 4], dtype=int32)>

In [62]:
a[2::-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 4, 2], dtype=int32)>

In [63]:
a = tf.random.normal([2, 4, 28, 28, 3])
a[0].shape

TensorShape([4, 28, 28, 3])

In [64]:
a[0, :, :, :, :].shape

TensorShape([4, 28, 28, 3])

In [65]:
a[0, ...].shape

TensorShape([4, 28, 28, 3])

In [66]:
a[..., 0].shape

TensorShape([2, 4, 28, 28])

In [67]:
a[0, ..., 2].shape

TensorShape([4, 28, 28])

In [68]:
a[1, 0, ..., 0].shape

TensorShape([28, 28])